# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/grpc/extractor/extractor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'v1/grpc/extractor/extractor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!v1/grpc/extractor/extractor.proto\x12\textractor\"\x8a\x01\n\x10\x45xtractorRequest\x12*\n\x0bupload_info\x18\x01 \x01(\x0b\x32\x15.extractor.UploadInfo\x12\x19\n\x11process_rule_mode\x18\x02 \x01(\t\x12\x17\n\x0f\x64\x61tasource_type\x18\x03 \x01(\t\x12\x16\n\x0e\x64ocument_model\x18\x04 \x01(\t\"@\n\nUploadInfo\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x12\n\ncreated_by\x18\x03 \x01(\t\"X\n\x0e\x45xtractorReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x11\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12+\n\tdocuments\x18\x03 \x03(\x0b\x32\x18.extractor.DocumentReply\"\xa3\x01\n\rDocumentReply\x12\x14\n\x0cpage_content\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t\x12\x39\n\tmeta_data\x18\x03 \x03(\x0b\x32&.extractor.DocumentReply.MetaDataEntry\x1a/\n\rMetaDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32P\n\tExtractor\x12\x43\n\x07\x65xtract\x12\x1b.extractor.ExtractorRequest\x1a\x19.extractor.ExtractorReply\"\x00\x42.\n\x13lune.grpc.extractorB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.grpc.extractor.extractor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023lune.grpc.extractorB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_DOCUMENTREPLY_METADATAENTRY']._loaded_options = None
  _globals['_DOCUMENTREPLY_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EXTRACTORREQUEST']._serialized_start=49
  _globals['_EXTRACTORREQUEST']._serialized_end=187
  _globals['_UPLOADINFO']._serialized_start=189
  _globals['_UPLOADINFO']._serialized_end=253
  _globals['_EXTRACTORREPLY']._serialized_start=255
  _globals['_EXTRACTORREPLY']._serialized_end=343
  _globals['_DOCUMENTREPLY']._serialized_start=346
  _globals['_DOCUMENTREPLY']._serialized_end=509
  _globals['_DOCUMENTREPLY_METADATAENTRY']._serialized_start=462
  _globals['_DOCUMENTREPLY_METADATAENTRY']._serialized_end=509
  _globals['_EXTRACTOR']._serialized_start=511
  _globals['_EXTRACTOR']._serialized_end=591
# @@protoc_insertion_point(module_scope)
